version: '3'

volumes:
  db-data:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker-data/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./docker-data/nginx/ssl/bikesharing.loc.crt:/etc/nginx/certs/bikesharing.loc.crt
      #- ./docker-data/nginx/ssl/bikesharing.loc.key:/etc/nginx/certs/bikesharing.loc.key
    ports:
      - 80:80
      #- 443:443
    links:
      - web
  db:
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bikesharing
      MYSQL_USER: bikesharing
      MYSQL_PASSWORD: password
    volumes:
      - ./docker-data/mysql:/docker-entrypoint-initdb.d
      - ./docker-data/mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./db-data:/var/lib/mysql
  web:
    build: .
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www/html/
      - ./docker-data/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker-data/php/override.ini:/usr/local/etc/php/conf.d/override.ini
    depends_on:
      - db
    extra_hosts:
      - host.docker.internal:host-gateway
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 81:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
      - UPLOAD_LIMIT=30M
