# Group Me


# me endpoints [/api/me/]

## Profile [GET /api/me]

+ Response 200 (application/json)

   + Attributes (User)


## Closest stands [GET /api/me/closest-stands]
Closest stands for my current gps location

+ Response 200 (application/json)

   + Attributes (Stand)
