# Auth [/auth]
Auth.

## POST /api/auth/authenticate
+ Request aaa (application/json)
    + Headers
    	Accept: application/json
    + Body
		{
			"phone_number": "+4210944244393",
			"password": "password"
		}
+ Response 200 (application/json)

    + Attributes (array[Question])
