FORMAT: 1A
HOST: http://whitebikes.dev

# BikeShare API



# Group Authentication
App auth

# Auth [/api/auth/]

## Login [POST /api/auth/authenticate]
+ Request (application/json)
    + Headers
    	Accept: application/json
    + Body
		{
			"phone_number": "+4210944244393",
			"password": "password"
		}
+ Response 200 (application/json)

    + Body
    	{
    		"token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIVzI1NiJ9.eyJpc3MiOiJodHRwOi8vd2hpdGViaWtlcy5kZXYvYXBpL2F1dGgvYXV0aGVudGljYXRlIiwiaWF0IjoxNDc1Mzk0MjM5LCJuYmYiOjE0NzUzOTQyMzksImp0aSI6Ijk1MzAzZDczMmYzYzBhYjJlYzU4N2MxZTA2YzU4YjA4Iiwic3ViIjoxfQ.Z0_EkP4GfutCUBraCL_FhGotPoKDswuZ6baMJY3_0Os"
    	}

## Register [POST /api/auth/register]
+ Request (application/json)
    + Headers
    	Accept: application/json
    + Body
		{
			"name": "John Doe",
			"email": "john@doe.com",
			"phone_number": "+421944244303",
			"password": "heslo"
		}
+ Response 200 (application/json)

    + Attributes (User)

## Data Structures

### User
+ uuid: `4eacbd40-707b-11e6-8440-6b0424d4dc06`
+ name: John Doe
+ phone_number: +421944244303
+ email: john@doe.com
+ note: some notes
+ recommendation: some recommendation
