## Data Structures

### User
+ uuid: `4eacbd40-707b-11e6-8440-6b0424d4dc06`
+ name: John Doe
+ phone_number: +421944244303
+ email: john@doe.com
+ note: some notes
+ recommendation: some recommendation
