## Data Structures

### User
+ uuid: `4eacbd40-707b-11e6-8440-6b0424d4dc06`
+ name: John Doe
+ phone_number: +421944244303
+ email: john@doe.com
+ note: some notes
+ recommendation: some recommendation
+ credit: 300.00 (number, required)
+ credit_currency: €
+ limit: 1 (number, required)
+ created_at: `2016-09-01 08:02:22`


### Stand
+ data
	+ uuid: `a4c6cff7-297c-436e-b08b-1a4160184323`
	+ name: Saleziani
	+ latitude: 48.15495 (number)
	+ longitude: 17.13446 (number)
	+ photo: null
	+ description: dsdsdss
	+ place_name: Miletocova
	+ status: active (string)
	+ distance: 190 (number)
